// Auto-generated by scripts/generate-rule-registry.ts. Do not edit manually.
import type { Rule } from '../types';
import { astroIslandLeakRule } from './arch/astro-island-leak';
import { shadcnPropMismatchRule } from './component/shadcn';
import { spacingGridRule } from './layout/spacing-grid';
import { boundaryViolationRule } from './logic/boundary-violation';
import { consoleLogRule } from './logic/console-log';
import { ghostDefensiveRule } from './logic/ghost-defensive';
import { qwikHookLeakRule } from './logic/qwik-hook-leak';
import { reactiveHookSoupRule } from './logic/reactive-hook-soup';
import { styleSheetAvoidanceRule } from './logic/style-sheet-avoidance';
import { zombieStateRule } from './logic/zombie-state';
import { clsImageRule } from './perf/cls-image';
import { calcFontSizeRule } from './typo/calc-fontsize';
import { calcRawPxRule } from './typo/calc-raw-px';
import { clampOffscaleRule } from './typo/clamp-offscale';
import { placeholderTextRule } from './typo/placeholder-text';
import { arbitraryEscapeRule } from './visual/arbitrary-escape';
import { clampSoupRule } from './visual/clamp-soup';
import { forcedLayoutRule } from './visual/forced-layout';
import { genericCenteringRule } from './visual/generic-centering';
import { hardcodedColorRule } from './visual/hardcoded-color';
import { inlineStyleRule } from './visual/inline-style';
import { rawStyleValuesRule } from './visual/raw-style-values';
import { colorContrastRule } from './wcag/color-contrast';
import { draggingMovementsRule } from './wcag/dragging-movements';
import { focusAppearanceRule } from './wcag/focus-appearance';
import { focusObscuredRule } from './wcag/focus-obscured';
import { targetSizeRule } from './wcag/target-size';

export const builtinRules: Rule[] = [
  astroIslandLeakRule,
  shadcnPropMismatchRule,
  spacingGridRule,
  boundaryViolationRule,
  consoleLogRule,
  ghostDefensiveRule,
  qwikHookLeakRule,
  reactiveHookSoupRule,
  styleSheetAvoidanceRule,
  zombieStateRule,
  clsImageRule,
  calcFontSizeRule,
  calcRawPxRule,
  clampOffscaleRule,
  placeholderTextRule,
  arbitraryEscapeRule,
  clampSoupRule,
  forcedLayoutRule,
  genericCenteringRule,
  hardcodedColorRule,
  inlineStyleRule,
  rawStyleValuesRule,
  colorContrastRule,
  draggingMovementsRule,
  focusAppearanceRule,
  focusObscuredRule,
  targetSizeRule,
];
